"""Update tabla Users

Revision ID: 22c125208968
Revises: 01584ced2d96
Create Date: 2025-03-18 11:45:23.105948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22c125208968'
down_revision = '01584ced2d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_index('ix_user_refresh_token')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('backup_codes')
        batch_op.drop_column('secret_2fa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_2fa', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('backup_codes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_user_refresh_token', ['refresh_token'], unique=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
