"""adicionar tablas2

Revision ID: 5b5354e13996
Revises: d727599a0cff
Create Date: 2025-05-20 23:27:33.359098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5354e13996'
down_revision = 'd727599a0cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=30), nullable=True),
    sa.Column('load_date', sa.DateTime(), nullable=True),
    sa.Column('load_location', sa.String(length=255), nullable=True),
    sa.Column('load_address', sa.String(length=255), nullable=True),
    sa.Column('load_city', sa.String(length=100), nullable=True),
    sa.Column('load_postal_code', sa.String(length=20), nullable=True),
    sa.Column('delivery_location', sa.String(length=255), nullable=True),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('delivery_city', sa.String(length=100), nullable=True),
    sa.Column('delivery_postal_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_number')
    )
    op.create_table('transport_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=30), nullable=True),
    sa.Column('load_date', sa.DateTime(), nullable=True),
    sa.Column('load_location', sa.String(length=255), nullable=True),
    sa.Column('load_address', sa.String(length=255), nullable=True),
    sa.Column('load_city', sa.String(length=100), nullable=True),
    sa.Column('load_postal_code', sa.String(length=20), nullable=True),
    sa.Column('delivery_location', sa.String(length=255), nullable=True),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('delivery_city', sa.String(length=100), nullable=True),
    sa.Column('delivery_postal_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport_guides')
    op.drop_table('shipping_guides')
    # ### end Alembic commands ###
