"""adicionar tablas2

Revision ID: aa17bb48b4e1
Revises: 5b5354e13996
Create Date: 2025-05-20 23:40:19.082672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa17bb48b4e1'
down_revision = '5b5354e13996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_note_number', sa.String(length=50), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('delivery_location', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('series', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('retention_percent', sa.Float(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_note_number')
    )
    op.create_table('order_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_note_number', sa.String(length=50), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('delivery_location', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('series', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('retention_percent', sa.Float(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('taxable_base', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('retention', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_note_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_notes')
    op.drop_table('delivery_notes')
    # ### end Alembic commands ###
